katka/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from profile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('signup/', include('signup.urls')),
    path('main/', include('main.urls')),
    path('profile/', include('profile.urls')),
    path('users/', include('users.urls')),
    path('messenger/', include('messenger.urls')),
    path('login/', views.index, name='login'),
    path('signup/', views.index, name='signup'),
    path('katkamessages/', include('katkamessages.urls', namespace='katkamessages')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

katkamessages/urls.py
from django.urls import path
from django.conf.urls import url


from .views import MessageCreateView

urlpatterns = [
    path('create/<str:content_type>/<int:object_id>/', MessageCreateView.as_view(), name='message-create')
]

app_name = 'katkamessages'

main/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^table/$', views.index, name='main'),
    url(r'^katka/(?P<pk>\d+)/$', views.katka_page, name='katka'),
    url(r'^create_katka/$', views.create_katka, name='create_katka'),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from profile.models import Profile
from .activities import ACTIVITY
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation


class Katka(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    city = models.CharField(max_length=150)
    date = models.DateField(max_length=150)
    time = models.TimeField(max_length=150)
    descr = models.CharField(max_length=350)
    katka_act = MultiSelectField(choices=ACTIVITY)
    members = models.ManyToManyField(Profile, related_name="profile_set")
    comments = GenericRelation('katkamessages.KatkaMessage')

    def get_absolute_url(self):
        return reverse('katka', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Катка'
        verbose_name_plural = 'Все события Катка'
        ordering = ['-id']

#
# class ChatMessage(models.Model):
#     """
#     Модель для представления сообщения чата
#     """
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     message = models.TextField(max_length=3000)
#     message_html = models.TextField()
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return self.message

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Katka


class KatkaForm(forms.ModelForm):
    class Meta:
        model = Katka
        fields = ('id', 'city', 'date', 'time', 'descr', 'katka_act', 'author',)


class KatkaEntryForm(forms.ModelForm):
    class Meta:
        model = Katka
        fields = ('members',)

main/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from .forms import KatkaForm, KatkaEntryForm
from .models import Katka
from django.db import connection
from django.contrib.auth.models import User
from profile.models import Profile


def index(request):
    ktk = Katka.objects.all()
    return render(request, 'main/main.html', {"ktk": ktk})


def katka_page(request, pk):
    global ktk_item
    ktk_item = Katka.objects.get(pk=pk)
    # начальный статус 0 - пользователь не участвует в катке
    status = 0

    if request.method == 'POST':
        profile = Profile.objects.get(user_id=request.user.id)
        ktk_item.members.add(profile)
        return redirect(ktk_item)

    # Проверяем, если id пользователя находиься в таблице участников, меняем статус на 1 и
    # в условии шаблона если статус == 1 показать кнопку участвую, иначе Вступить
    for i in ktk_item.members.all():
        if i.pk == request.user.id:
            status = 1

    return render(request, 'katka_page/katka_page.html',
                  {"ktk_item": ktk_item, "status": status})


def create_katka(request):
    poster = request.user

    if request.method == 'POST':
        form = KatkaForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = poster
            form.save()
            return redirect('main')
        else:
            print(form.errors)
    else:
        form = Katka()

    return render(request, 'create_katka/create_katka.html', {'form': form})

main/templates/katka_page/katka_page.html
{% extends 'base_katka.html' %}

{% block title %}
    <title>KATKA ID:{{ ktk_item.id }} | г.{{ ktk_item.city }}</title>
{% endblock %}

{% block links %}
    {{ block.super }}
    {% load static %}
    {% load crispy_forms_tags %}
    <link rel="stylesheet" type="text/css" href="{% static 'katka_page/css/katka_page.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'katka_page/css/katka_chat.css' %}"/>

{% endblock %}

{% block content %}
    <div class="div-block">
        <div class="columns w-row">
            <div class="column-4 w-col w-col-7 w-col-medium-7">
                <div class="div-block-21">
                    <div class="div-block-42">
                        <div>
                            <div class="div-block-35">
                                <div class="text-block-25">ID: {{ ktk_item.id }}</div>
                            </div>
                        </div>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if status == 1 %}
                                <div class="div-block-46">
                                    <button class="button-10 w-button" type="button" data-bs-toggle="tooltip"
                                            data-bs-placement="right" title="Нельзя покинуть :(">
                                        <img src="{% static 'img/check_button.png' %}" width="15" height="15" alt="">
                                        Участвую
                                    </button>
                                </div>
                            {% else %}
                                <button class="button-4 w-button" type="submit">Вступить</button>
                            {% endif %}
                        </form>
                        {# <div class="div-block-46"><a href="#" class="button-10 w-button">Покинуть</a></div>#}
                        {# <div class="div-block-46"><a href="#" class="button-4 w-button">Пригласить</a></div>#}
                        <div class="div-block-43">
                            {% if ktk_item.katka_act %}
                                {% for item in ktk_item.katka_act %}
                                    <div class="block-act">
                                        <img class="kp_img" src="{% static item %}" alt="">
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="div-block-49">
                        <div>Организатор:</div>
                        <a href="{% url 'some' ktk_item.author.pk %}"
                           class="link-5">{{ ktk_item.author.first_name }} {{ ktk_item.author.last_name }}</a></div>
                </div>
                <div class="div-block-29">
                    <div class="columns-16 w-row">
                        <div class="column-29 w-col w-col-4">
                            <div>
                                <div class="text-block-22">Город:</div>
                            </div>
                            <div class="section-23">
                                <div class="text-block-15">{{ ktk_item.city }}</div>
                            </div>
                        </div>
                        <div class="w-col w-col-4">
                            <div>
                                <div class="text-block-22">Дата:</div>
                            </div>
                            <div class="section-24">
                                <div class="text-block-15">{{ ktk_item.date }}</div>
                            </div>
                        </div>
                        <div class="w-col w-col-4">
                            <div>
                                <div class="text-block-22">Время:</div>
                            </div>
                            <div class="section-25">
                                <div class="text-block-15">{{ ktk_item.time }}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="div-block-45"><p class="paragraph-2">{{ ktk_item.descr }}</p></div>
                </div>
                <div class="div-block-23">
                    <div class="section-9"><h5 class="heading-4">Length: 123 km.</h5><img
                            src="https://uploads-ssl.webflow.com/5f1d72d3a5d4074a78fb17c3/5f358f5ebe8534b3f1ac7172_map-marker-2-128.png"
                            width="20" alt=""/><h5 class="heading-3">Москва, Россия</h5></div>
                    <div class="section-12">
                        <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Ad47277beca50469695ff4b31803d8e5a10e235c9b818a64e3834c43c844824e3&amp;source=constructor"
                                width="100%" height="350" frameborder="0"></iframe>
                    </div>
                </div>
                <div>
                    <div class="section-22">
                        <blockquote class="block-quote-3">Все участники <span
                                class="badge badge-secondary">{{ ktk_item.members.count }}</span> :
                        </blockquote>
                    </div>
                    <div class="container-7 w-container" style="float: left">
                        {% for item in ktk_item.members.all %}
                            <div class="div-block-44">
                                <a href="{% url 'some' item.pk %}">
                                    <div class="section-19">
                                        {% if item.avatar %}
                                            <img src="{{ item.avatar.url }}" loading="lazy" width="50" height="50"
                                                 alt="" class="imagew-22"/>
                                        {% else %}
                                            <img src="{% static 'img/user.png' %}" loading="lazy" width="50" height="50"
                                                 alt="" class="imagew-22"/>
                                        {% endif %}
                                    </div>
                                    <div class="section-20">
                                        <div class="username">{{ item.user.first_name }} {{ item.user.last_name }}</div>
                                    </div>
                                </a>
                                <div class="usertown">{{ item.city }} </div>
                            </div>
                        {% endfor %}
                    </div>
                    {#                {% for item in ktk_item.members.all %}#}
                    {#                       {{ item.user.first_name }}             Перебор по User#}
                    {#                       {{ item.city }}                        Перебор по Profile#}
                    {#                {% endfor %}#}
                </div>

            </div>
            <div class="column w-col w-col-5 w-col-medium-5">
                <div class="w-form">
                    <div class="div-block-41">
                        <div class="cht-block">
                            <div id="convo">
                                <div class="chatroom-title">
                                    <text>Чат комнаты ID: {{ ktk_item.id }}</text>
                                    <hr>
                                </div>
                                <div class="dv_chat" id="comments-list">
                                    {% for message in ktk_item.comments.all %}
                                        <div class="col-md-12 mt-3 mb-3">
                                            <div class="chatblock">
                                                <div class="chatimage">
                                                    <div class="section-19">
                                                        <a href="{% url 'some' message.author.pk %}">
                                                            {% if message.author.profile.avatar %}
                                                                <img src="{{ message.author.profile.avatar.url }}"
                                                                     loading="lazy" width="50"
                                                                     height="50"
                                                                     alt="" class="imagew-22"/>
                                                            {% else %}
                                                                <img src="{% static 'img/user.png' %}" loading="lazy"
                                                                     width="50" height="50"
                                                                     alt="" class="imagew-22"/>
                                                            {% endif %}
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="chatdata">
                                                    <a href="{% url 'some' message.author.pk %}">
                                                        <div class="username2">
                                                            {{ message.author.first_name }} {{ message.author.last_name }}
                                                        </div>
                                                    </a>
                                                    <p>{{ message.text }}</p>
                                                    <small>{{ message.created_at|date:"d-m-Y" }} {{ message.created_at|time:"H:i" }}</small>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'katkamessages:message-create' content_type="katka" object_id=ktk_item.pk %}"
                          method="POST">
                        {% csrf_token %}
                        <div class="section-21">
                            <textarea name="text" class="form-control" id="chat-message-input"
                                      rows="1"></textarea>
                            <input id="chat-message-submit" type="submit" value="Отправить"
                                   class="submit-button-4 w-button"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5f1d72d3a5d4074a78fb17c3"
            type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"></script>
    <script src="https://uploads-ssl.webflow.com/5f1d72d3a5d4074a78fb17c3/js/webflow.91ed54993.js"
            type="text/javascript"></script>
    <!--[if lte IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->

    <script>
        {#Первичный скролл всего чата к последнему сообщению#}
        var element = document.getElementById('comments-list');
        element.scrollTop = element.scrollHeight;

        const roomName = {{ ktk_item.id }};

        const commentsSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/main/katka/'
            + roomName
            + '/'
        );

        commentsSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            commentsList = document.getElementById('comments-list')
            commentsList.insertAdjacentHTML(
                'beforeend',
                '<div class="col-md-12 mt-3 mb-3">\n' +
                '<div class="chatblock">\n' +
                '<div class="chatimage">\n' +
                '<div class="section-19">\n' +
                '</div>' +
                '</div>' +
                '<div class="chatdata">' +
                '<div class="username2">' +
                data['message']['author_f'] + ' ' + data['message']['author_l'] + '\n' +
                '</div>' +
                '<p>' + data['message']['text'] + '</p>' + '\n' +
                '<small>' + data['message']['created_at'] + '</small>' +
                '</div>' +
                '</div>' +
                '</div>'
            )
            {#Скролл при добавлении каждого сообщения#}
            var element = document.getElementById('comments-list');
            element.scrollTop = element.scrollHeight;
        };


        document.querySelector('#chat-message-submit').onclick = function (e) {
            e.preventDefault()
            const messageInputDom = document.querySelector('#chat-message-input');
            const text = messageInputDom.value;
            commentsSocket.send(JSON.stringify({
                'text': text
            }));
            messageInputDom.value = '';
        };
    </script>


{% endblock %}